// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLv9Mr_YZ6f4CzBCPVgeoPaJ3RrEj5gQ',
    appId: '1:546240967899:android:4026359b29d78efcca48fe',
    messagingSenderId: '546240967899',
    projectId: 'jarvis-78573',
    storageBucket: 'jarvis-78573.firebasestorage.app',
  );

  // Web (Flutter Web PWA for Rakhi — jarvis-78573.web.app).
  // Registered 2026-04-23 via Firebase Console → Add app → Web ("Rakhi PWA").
  // Values below match the firebaseConfig block shown in the console; they
  // must also match web/firebase-messaging-sw.js exactly, otherwise the
  // service worker subscribes to a different project than the app and
  // push tokens silently stop being delivered.
  //
  // The Android block above is untouched by this web-app registration —
  // they're two separate Firebase app entries in the same project.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzulGhpmhq1EuYlIvz0eMsmvgvD1qh3M',
    appId: '1:546240967899:web:21f2901d31e2b15dca48fe',
    messagingSenderId: '546240967899',
    projectId: 'jarvis-78573',
    storageBucket: 'jarvis-78573.firebasestorage.app',
    authDomain: 'jarvis-78573.firebaseapp.com',
    measurementId: 'G-H565RT71Y9',
  );
}
