// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLv9Mr_YZ6f4CzBCPVgeoPaJ3RrEj5gQ',
    appId: '1:546240967899:android:4026359b29d78efcca48fe',
    messagingSenderId: '546240967899',
    projectId: 'jarvis-78573',
    storageBucket: 'jarvis-78573.firebasestorage.app',
  );

  // Web (Flutter Web PWA for Rakhi — jarvis-78573.web.app).
  //
  // FIXME: `appId` must be filled in before the first web deploy.
  //   1. Firebase Console → jarvis-78573 → Project settings → General
  //      → "Your apps" → Add app → Web.
  //   2. Register the app with a nickname (e.g. "Rakhi PWA"), copy
  //      the `appId` value out of the generated firebaseConfig snippet.
  //   3. Paste it below (replaces WEB_APP_ID).
  //   4. In the same panel, grab the web `apiKey` — it's distinct from
  //      the Android one — and paste into `apiKey` below.
  //   5. Also copy the same config into web/firebase-messaging-sw.js.
  //   6. Under Cloud Messaging → Web Push certificates, generate a
  //      VAPID key pair and paste the PUBLIC key into env.web.json
  //      as VAPID_PUBLIC_KEY.
  //
  // The Android block above is untouched by any web-app registration.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLv9Mr_YZ6f4CzBCPVgeoPaJ3RrEj5gQ', // FIXME replace with web apiKey
    appId: '1:546240967899:web:WEB_APP_ID_PENDING_CONSOLE_REGISTRATION',
    messagingSenderId: '546240967899',
    projectId: 'jarvis-78573',
    storageBucket: 'jarvis-78573.firebasestorage.app',
    authDomain: 'jarvis-78573.firebaseapp.com',
  );
}
