// This file will be generated by FlutterFire CLI
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

// TODO: Run FlutterFire CLI to generate this file
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'DefaultFirebaseOptions have not been configured for this platform. '
      'Run "flutterfire configure" to generate firebase_options.dart',
    );
  }
}